package business.rules;

import com.technorage.demo.facts.RuleSetup;
import com.technorage.demo.facts.RulePrecedence;

/*
rule "Decide Winning Rule"
	salience -100
	when
		$list: List($rules: ruleSetup) 
       	$setup: RuleSetup(isQualified) from $list
       
	then
		System.out.println("Offer " + $setup.getRuleNumber());
end	*/

rule "Define priority P1 on basis of overridenExplicitly flag"
	salience -50
	enabled($r.winningPriority == "")
	when
		$r: RuleSetup(isQualified, offer.overridenExplicitly)
	then
		modify($r){
			setWinningPriority("P1");
		}
end

rule "Define priority P2 on basis of hardcode flag"
	salience -50
	enabled($r.winningPriority == "")
	when
		$r: RuleSetup(isQualified, offer.hardcode, !offer.overridenExplicitly)
	then
		modify($r){
			setWinningPriority("P2");
		}
end

rule "Assign prioriy flag on basis of overriden flag"
	no-loop
	enabled($r.winningPriority == "")
	when
		$rulePrecedence: RulePrecedence()
		$r: RuleSetup(isQualified, offer.overridenExplicitly, $rulePrecedence.ruleName.equals("overridenExplicitlyFlag"))
	then
		modify($r){
			setWinningPriority($rulePrecedence.getPriority());
		}
			
end

rule "Assign prioriy flag on basis of hardcode flag"
	no-loop
	enabled($r.winningPriority == "")
	when
		$rulePrecedence: RulePrecedence()
		$r: RuleSetup(isQualified, offer.hardcode, $rulePrecedence.ruleName.equals("hardcodeFlag"))
	then
		modify($r){
			setWinningPriority($rulePrecedence.getPriority());
		}
			
end

rule "Decide winner on basis of combo field"
	salience -100
	when
		$r: RuleSetup(isQualified, offer.comboField == 2, !isWinner)
	then
     	modify($r){
			setIsWinner(true);
		}
			
end

