package business.rules;

import com.technorage.demo.facts.RuleSetup;
import com.technorage.demo.facts.StandardRuleSetup;


rule "Rule if Account Number, Family Code Match"
    no-loop
    when  
       	$o: OrderLine()  
       	$r: RuleSetup(!isQualified, account.accountNumber == $o.account.accountNumber, product.familyCode.equals($o.product.familyCode),
       		qtyDiscountMap.size() > 0)
       	
   then  
     	System.out.println("Rule with discount entered: " + $r.getRuleName());
     	modify($r){
     		setIsQualified(true);
     	}
     
end

rule "Rule if Account Number blank, Family Code Match"
    no-loop
    when  
       	$o: OrderLine()  
       	$r: StandardRuleSetup(!isQualified, product.familyCode.equals($o.product.familyCode),
       		qtyDiscountMap.size() > 0)
       	
   then  
     	System.out.println("Rule with no account entered: " + $r.getRuleName());
     	modify($r){
     		setIsQualified(true);
     	}
     
end



